fix: Enforce project creation to access dashboard
piyushgarg-dev/review-app pull request #268
Opened 2023-10-26 22:35 UTC by ruhani2

## What does this PR do?

Mandates users to create project for dashboard access

Fixes #91

- **New Signup** (no projects yet)
https://watch.screencastify.com/v/FDRKMV4MqzvbKPp2ySNq

- **SignIn** (no projects yet), will take care existing users without any projects
https://watch.screencastify.com/v/KM4eugqnTFFiqVlSTuRh

- **Login after project is already created**
https://watch.screencastify.com/v/2BghLyEPDc6O1TsLa13i

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

Same process shown in above videos

## Mandatory Tasks

- [ ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

2023-10-27 12:57 UTC, ruhani2 commented
@hemantwasthere  can you please also add hacberfest-accepted label if it is accepted.

2023-10-29 11:08 UTC, hemantwasthere commented
Hey @ruhani2 I saw your changes it seems good but we want to open the create project modal the moment user gets signed up and redirected to dashboard

2023-10-29 11:44 UTC, hemantwasthere requested changes
LGTM but can you also protect `http://app.localhost:3000/dashboard/{domain}` route so that user can't access this route as well without creating a project

2023-10-29 14:50 UTC, ruhani2 commented
> LGTM but can you also protect `http://app.localhost:3000/dashboard/{domain}` route so that user can't access this route as well without creating a project

Thank you for pointing this out. I have updated the code so that it ensures project creation for other pages within the dashboard.

<img width="1440" alt="Screenshot 2023-10-29 at 8 08 53 PM" src="https://github.com/piyushgarg-dev/review-app/assets/13129596/a63b0105-57d8-417c-b807-27153d23a42a">
<img width="1440" alt="Screenshot 2023-10-29 at 8 08 45 PM" src="https://github.com/piyushgarg-dev/review-app/assets/13129596/c38efaf7-b3cc-408f-b90a-28ae14da02ae">

Please let me know if you have any other suggestions.

2023-10-30 05:48 UTC, hemantwasthere requested changes

2023-10-30 05:48 UTC, hemantwasthere commented on wrappers/DashboardAccessWrapper.tsx
> +  }, [pathname])
please add `projects` in the dep array as well

2023-10-31 13:00 UTC, hemantwasthere approved these changes
Looks good!

2023-10-31 13:00 UTC, hemantwasthere commented
Thanks for your contribution @ruhani2 🚀

2023-10-31 13:01 UTC, merged